-- Phase 3A migration: change ai_confidence from smallint (0–100) to numeric(4,3) (0.000–1.000)
--
-- Run this against your Supabase project via the SQL editor or CLI:
--   supabase db push   (if using local dev)
--   or paste into Supabase Dashboard → SQL Editor

-- 1. Drop the old check constraint (name generated by Postgres from the inline definition)
alter table expenses
  drop constraint if exists expenses_ai_confidence_check;

-- 2. Null-out any existing integer values that are out of the new 0–1 range.
--    Rows with values 0–100 stored as integers would all violate the new constraint,
--    so we clear them rather than attempt a lossy divide-by-100 on unknown data.
update expenses
  set ai_confidence = null
  where ai_confidence is not null;

-- 3. Change the column type
alter table expenses
  alter column ai_confidence type numeric(4,3) using ai_confidence::numeric(4,3);

-- 4. Add the new check constraint
alter table expenses
  add constraint expenses_ai_confidence_check
  check (ai_confidence is null or (ai_confidence >= 0 and ai_confidence <= 1));
